<?php

namespace App\Http\Requests\Api\Receivers;

use App\Http\Requests\BaseRequest;

class ReceiverStoreRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [
            'name' => 'required|string',
            'phone' => 'required|numeric|unique:receivers,phone',
            'receiving_company' => 'nullable|string',
            'branch_id' => 'required|numeric|exists:branches,id',
            'city_id' => 'required|numeric|exists:locations,id',
            'area_id' => 'required|numeric|exists:locations,id',
            'reference' => 'nullable|string|unique:receivers,reference',
            'title' => 'nullable|string',
            'notes' => 'nullable|string',
            'address' => 'required|array',
            'lat' => 'string|nullable',
            'lng' => 'string|nullable',
            'postal_code' => 'string|nullable',
            'map_url' => 'string|nullable',
            'is_default'=>'boolean|nullable',
        ];
    }

    public function validationData(): array
    {
        return array_merge($this->all(),['is_default'=>true]); // TODO: Change the autogenerated stub
    }
}
